android/library/src/main/java/io/logto/android/client/LogtoAndroidClient.kt
android/library/src/main/java/io/logto/client/model/TokenSet.kt

`Gson` will not call constructor of data class `TokenSet` during serialization process which makes us loose our expiresAt value in tokenSet. (ref: [Why Kotlin data classes can have nulls in non-nullable fields with Gson?](https://stackoverflow.com/questions/52837665/why-kotlin-data-classes-can-have-nulls-in-non-nullable-fields-with-gson))
Another 3rd json serialization lib intergated with ktor, Jackson, has the same problem.
We can use `kotlinx.serilazation.json` to solve this problem, but `kotlinx.serilazation.json` don't support [json properties naming configuration](https://github.com/Kotlin/kotlinx.serialization/issues/33).
So, we need to call `TokenSet`'s method `calculateExpiresAt` explicitly once we grant it from backend.
* [Bug: Gson should call `TokenSet`'s constructor …

fix: calculate tokenSet expiresAt on granted

---

android/library/src/main/java/io/logto/android/auth/AuthManager.kt
android/library/src/main/java/io/logto/android/auth/IFlow.kt
android/library/src/main/java/io/logto/android/auth/activity/AuthorizationActivity.kt
android/library/src/main/java/io/logto/android/auth/browser/BrowserSignInFlow.kt
android/library/src/main/java/io/logto/android/auth/browser/BrowserSignOutFlow.kt
android/library/src/main/java/io/logto/client/exception/LogtoException.kt
android/library/src/test/java/io/logto/android/auth/AuthManagerTest.kt
android/library/src/test/java/io/logto/android/auth/browser/BrowserSignInFlowTest.kt
android/library/src/test/java/io/logto/android/auth/browser/BrowserSignOutFlowTest.kt

* fix: should handle user cancel in browser flow
* [Fix: reset AuthManager on user cancel (LOG-326)](https://linear.app/silverhand/issue/LOG-326/fix-reset-authmanager-on-user-cancel)
1. UT
2. Test sample:

fix: should handle user cancel in browser flow

---

android/app/src/main/java/io/logto/demo/viewmodel/LogtoViewModel.kt
android/library/src/main/java/io/logto/client/LogtoClient.kt
android/library/src/main/java/io/logto/client/config/LogtoConfig.kt
android/library/src/test/java/io/logto/android/storage/TokenSetStorageTest.kt
android/library/src/test/java/io/logto/client/LogtoClientTest.kt
android/library/src/test/java/io/logto/client/config/LogtoConfigTest.kt

- Naming scope and scope values accurately. 
- Definitions
- `scope value` : one of `openid`, `name`, `email` & etc.
- `scope values` : array/list/set consisted of multiple `scope value`s
- e.g. `["openid", "name", "email"]`
- `scope` : the string consisted of `scope value`s joined by whitespaces
- a non-normative example of a scope Request: `scope=openid profile email phone`
_from https://www.rfc-editor.org/rfc/inline-errata/rfc6749.html session 3.3_
> The value of the scope parameter is expressed as a space-delimited list of case-sensitive strings.
- References : https://openid.net/specs/openid-connect-basic-1_0.html#Scopes
- Previous PR : https://github.com/logto-io/kotlin/pull/50
Pass all existing tests.

chore(android): accurate naming scope and scope values

---

android/library/src/main/java/io/logto/client/config/LogtoConfig.kt
android/library/src/test/java/io/logto/client/config/LogtoConfigTest.kt

- Url-encode the cache key as same as JS SDK does.
- But keep the default encoding rule of url-encoding in each environment
- JS `encodeURLComponent` whitespace → `%20`
- Java `java.net.URLEncoder.encode` : whitespace → `+`
- Original PR : https://github.com/logto-io/kotlin/pull/51
Pass all existing code.

chore(android): url-encode cacheKey as same as js-sdk

---

android/library/src/main/java/io/logto/android/client/LogtoAndroidClient.kt
android/library/src/main/java/io/logto/client/LogtoClient.kt
android/library/src/main/java/io/logto/client/model/TokenSet.kt
android/library/src/main/java/io/logto/client/model/TokenSetParameters.kt
android/library/src/main/java/io/logto/client/service/LogtoService.kt
android/library/src/test/java/io/logto/android/client/LogtoAndroidClientTest.kt
android/library/src/test/java/io/logto/android/storage/TokenSetStorageTest.kt
android/library/src/test/java/io/logto/client/LogtoClientTest.kt

* refactor: move token validation logic to `logtoClient`
* [refactor: move token validation logic to `logtoClient` (LOG-329)](https://linear.app/silverhand/issue/LOG-329/refactor-move-token-validation-logic-to-logtoclient)
UT

refactor: move token validation logic to `logtoClient`

---

android/library/src/main/java/io/logto/android/auth/AuthManager.kt
android/library/src/main/java/io/logto/android/auth/activity/AuthorizationActivity.kt
android/library/src/main/java/io/logto/android/auth/activity/RedirectUriActivity.kt

In a brand new device which haven't been launched chrome will cause our sdk start an custom tab and flush out immediately. Because we need to agree the TOS of chrome.
So, we should not launch our custom tab with flag [FLAG_ACTIVITY_SINGLE_TOP](https://developer.android.com/reference/android/content/Intent#FLAG_ACTIVITY_SINGLE_TOP) which will lead to launch tab before our agreement to chorme. this make our tab flush out.
And we don't need to launch custom tab with flag [FLAG_ACTIVITY_CLEAR_TOP](https://developer.android.com/reference/android/content/Intent#FLAG_ACTIVITY_CLEAR_TOP) for we launch tabs above our application every time.
If we start chrome custom tab with the progress of agreement of chrome's TOS. we will have multi activities in the background. we may navigate to our app …

fix: should start an customTab in a brand new device on sign in

---

android/build.gradle
android/library/build.gradle
android/library/src/main/java/io/logto/android/auth/browser/BrowserSignInFlow.kt
android/library/src/main/java/io/logto/client/LogtoClient.kt
android/library/src/main/java/io/logto/client/constant/QueryKey.kt
android/library/src/main/java/io/logto/client/exception/LogtoException.kt
android/library/src/main/java/io/logto/client/utils/GenerateUtils.kt
android/library/src/test/java/io/logto/android/auth/browser/BrowserSignInFlowTest.kt
android/library/src/test/java/io/logto/client/LogtoClientTest.kt
android/library/src/test/java/io/logto/client/utils/GenerateUtilsTest.kt

- feat(android): add state to signInUrl to prevent csrf attacking
- Related Notion doc : https://www.notion.so/silverhand/OAuth-2-0-Security-b7b1f43d5c784b599c084d3ff356525c
- Related PR : https://github.com/logto-io/js/pull/94
- refactor(android): update BrowserSignInFlowTest using MockK
- Reference : https://mockk.io/
- Pass all existing tests
- New cases in BrowserSignInFlowTest
- Manual Android client tests
- Succeeded to check `state` value
- Login successfully

feat(android): add state to signInUrl to prevent csrf attacking

---

android/build.gradle
android/library/build.gradle
android/library/src/test/java/io/logto/android/auth/AuthManagerTest.kt
android/library/src/test/java/io/logto/android/auth/browser/BrowserSignInFlowTest.kt
android/library/src/test/java/io/logto/android/auth/browser/BrowserSignOutFlowTest.kt
android/library/src/test/java/io/logto/android/client/LogtoAndroidClientTest.kt
android/library/src/test/java/io/logto/android/utils/UtilsTest.kt
android/library/src/test/java/io/logto/client/LogtoClientTest.kt

- Refactor: replace `Mockito` with `Mockk` in unit tests
- MockK supports mocking static methods and objects but Mockito cannot.
- References:
- Official homepage : https://mockk.io/
- [MockK：一款強大的 Kotlin Mocking Library (Part 1 / 4)](https://medium.com/joe-tsai/mockk-%E4%B8%80%E6%AC%BE%E5%BC%B7%E5%A4%A7%E7%9A%84-kotlin-mocking-library-part-1-4-39a85e42b8)
- [MockK：一款強大的 Kotlin Mocking Library (Part 2 / 4)](https://medium.com/joe-tsai/mockk-%E4%B8%80%E6%AC%BE%E5%BC%B7%E5%A4%A7%E7%9A%84-kotlin-mocking-library-part-2-4-4be059331110)
- [MockK：一款強大的 Kotlin Mocking Library (Part 3 / 4)](https://medium.com/joe-tsai/mockk-%E4%B8%80%E6%AC%BE%E5%BC%B7%E5%A4%A7%E7%9A%84-kotlin-mocking-library-part-3-4-79b40fb73964)
- [MockK：一款強大的 Kotlin Mocking Library (Part 4 / …

Refactor: replace `Mockito` with `Mockk` in unit tests

---

android/library/src/test/resources/logback.xml

- Disable the unnecessary MockK DEBUG logs in the test
- Reference: [Turn off logging - mockk/mockk](https://github.com/mockk/mockk/issues/37)
Pass all existing tests
Before: 
After:

chore: disable unnecessary MockK DEBUG logs in test

---

kotlin/build.gradle.kts

Detekt is a static code analyzer, but it doesn't support code formatting by default, we should add the `detekt-formatting` dependency if we want to detect code format.
Reference: https://detekt.github.io/detekt/#adding-more-rule-sets
* LOG-978
None.
@logto-io/eng

feat(core): code format detecting

---

kotlin/build.gradle.kts

detekt will generate reports under the build folder by default.
add config for detekt to disable reports.
None.
@logto-io/eng

chore(core): disable detekt reports

---

android/logto-client/src/main/kotlin/io/logto/sdk/android/LogtoClient.kt
kotlin/src/main/kotlin/io/logto/sdk/core/http/HttpCompletion.kt
kotlin/src/test/kotlin/io/logto/sdk/core/CoreFetchTest.kt

Because HttpCompetion and RetrieveCallback have the same param name `result`, using them together will be confusing, so rename the `HttpCompletion` param name to `response`.
None.
UT

refactor(core): rename param`result` to `response` in `HttpCompletion`

---

android/logto-client/src/main/kotlin/io/logto/sdk/android/LogtoClient.kt
android/logto-client/src/test/kotlin/io/logto/sdk/android/LogtoClientTest.kt

* refactor(android): make `LogtoClient.isAuthenticated()` become a getter
* LOG-1450
UT

refactor(android): make `LogtoClient.isAuthenticated()` become a getter

---

kotlin-sdk/kotlin/src/main/kotlin/io/logto/sdk/core/Core.kt
kotlin-sdk/kotlin/src/main/kotlin/io/logto/sdk/core/constant/PromptValue.kt
kotlin-sdk/kotlin/src/test/kotlin/io/logto/sdk/core/CoreTest.kt

refactor(core): use `login` as the value of the `prompt` in generate sign in uri
LOG-2149
UT

refactor(core): use `login` as the value of the `prompt` in generate sign in uri

---

android-sdk/android/src/main/kotlin/io/logto/sdk/android/auth/logto/LogtoWebViewSocialHandler.kt
android-sdk/android/src/main/kotlin/io/logto/sdk/android/auth/social/SocialSessionHelper.kt
android-sdk/android/src/main/kotlin/io/logto/sdk/android/auth/social/alipay/AlipaySocialSession.kt
android-sdk/android/src/main/kotlin/io/logto/sdk/android/auth/social/wechat/WechatSocialSession.kt
android-sdk/android/src/main/kotlin/io/logto/sdk/android/util/LogtoUtils.kt

feat(android-sdk): detect supported social connectors
* LOG-2178

feat(android-sdk): detect supported social connectors

---

android-sdk/android/src/main/kotlin/io/logto/sdk/android/util/LogtoUtils.kt
android-sdk/android/src/test/kotlin/io/logto/sdk/android/util/LogtoUtilsTest.kt

* test(android-sdk): add test for logto utils
Since we can not mock `System.currentTimeMillis`, so use `Calendar` instead.
https://github.com/mockk/mockk/issues/98
* LOG-2226
UT

test(android-sdk): add test for logto utils

---

android-sdk/android/src/main/kotlin/io/logto/sdk/android/extension/LogtoConfigExt.kt
android-sdk/android/src/test/kotlin/io/logto/sdk/android/LogtoClientTest.kt
android-sdk/android/src/test/kotlin/io/logto/sdk/android/extension/LogtoConfigExtKtTest.kt

* feat(android-sdk): use uri uonstructor to construct oidc config endpoint
* make all related tests run with `RobolectricTestRunner` for we need to support the `android.net.Uri` to be run in JVM when running UTs.
* LOG-2241
UT

feat(android-sdk): use uri constructor to construct oidc config endpoint

---

kotlin-sdk/kotlin/src/test/kotlin/io/logto/sdk/core/CoreFetchTest.kt
kotlin-sdk/kotlin/src/test/kotlin/io/logto/sdk/core/constant/ConstantTest.kt
kotlin-sdk/kotlin/src/test/kotlin/io/logto/sdk/core/extension/JwtClaimsExtKtTest.kt

* tests for constants
* cover the null check branch in `fetchTokenByAuthorizationCode` and `fetchTokenByRefreshToken`
* `JwtClaims` extension
We can't not mock inline functions in mockk, so the functions under the `http` package can not be tested directly. we test these functions by setting up a mock server and testing the fetch function in `CoreFetchTest`.
Reference: [Cannot objectMockk inline function](https://github.com/mockk/mockk/issues/55)
* LOG-2225
UT

test(core): add missing tests for core

---

android-sdk/android/src/main/kotlin/io/logto/sdk/android/auth/social/web/WebSocialSession.kt
android-sdk/android/src/test/kotlin/io/logto/sdk/android/auth/social/web/WebSocialSessionTest.kt

* test(android-sdk): add ut for logto web social session
use `encodedQuery` in `Uri` construction for we will get an encoded string in the final URI string.
expected -> `'code=testCode'`
query -> `'code%3DtestCode'`
encodedQuery -> `'code=testCode'`
* LOG-2226
UT

test(android-sdk): web social session

---

android-sdk/android/src/test/kotlin/io/logto/sdk/android/storage/PersistStorageTest.kt

test(android-sdk): persist storage
* LOG-2226
UT

test(android-sdk): persist storage

---

android-sample-java/app/src/main/java/io/logto/demo4j/fragment/LoginFragment.java
android-sample-java/app/src/main/java/io/logto/demo4j/viewmodel/LogtoViewModel.java
android-sample-kotlin/app/src/main/kotlin/io/logto/android/sample4k/fragment/LoginFragment.kt
android-sample-kotlin/app/src/main/kotlin/io/logto/android/sample4k/viewmodel/LogtoViewModel.kt
android-sdk/android/src/main/kotlin/io/logto/sdk/android/LogtoClient.kt
android-sdk/android/src/test/kotlin/io/logto/sdk/android/LogtoClientTest.kt

Our sign-in method will invoke the sign-in process by the webView, browser, or native, so rename `signInWithBrowser` to `signIn`.
N/A
UT

refactor(android-sdk): `signInWithBrowser` -> `signIn`

---

android-sdk/android/src/main/AndroidManifest.xml

Since the webView activity will reload the page when configuration changes, so disable the configuration change process logic to keep our login page state.
Refer to: https://developer.android.com/guide/topics/resources/runtime-changes
N/A
Test in the sample app.

fix(android-sdk): disable web view activity configuration change

---

android-sample-java/app/src/main/java/io/logto/demo4j/viewmodel/LogtoViewModel.java
android-sdk/android/src/main/kotlin/io/logto/sdk/android/LogtoClient.kt
android-sdk/android/src/main/kotlin/io/logto/sdk/android/auth/logto/LogtoAuthSession.kt
android-sdk/android/src/main/kotlin/io/logto/sdk/android/exception/LogtoException.kt
android-sdk/android/src/main/kotlin/io/logto/sdk/android/type/LogtoConfig.kt
android-sdk/android/src/test/kotlin/io/logto/sdk/android/LogtoClientTest.kt
android-sdk/android/src/test/kotlin/io/logto/sdk/android/auth/logto/LogtoAuthSessionTest.kt
kotlin-sdk/kotlin/src/main/kotlin/io/logto/sdk/core/Core.kt
kotlin-sdk/kotlin/src/main/kotlin/io/logto/sdk/core/constant/PromptValue.kt
kotlin-sdk/kotlin/src/main/kotlin/io/logto/sdk/core/type/CodeTokenResponse.kt
kotlin-sdk/kotlin/src/test/kotlin/io/logto/sdk/core/CoreTest.kt

`prompt` value setup is now supported by our SDK.
* Change the refresh token in the `CodeTokenResponse` to be optional for we won't get a refresh token from it if the prompt value is `login`.(Refer to: https://silverhand-io.slack.com/archives/C02A8G4HVAM/p1649906832335309)
* Change the error returned from `NO_REFRESH_TOKEN_FOUND` to `NOT_AUTHENTICATED` in the `getAccessToken` method when this method cannot retrieve a valid access token and try to refresh for a new one, but no refresh token is valid. (Refer to: https://silverhand-io.slack.com/archives/C02A8G4HVAM/p1655869439813809)
* Fix Bug: `signOut` method in the `LogtoClient` should complete the process when no refresh token is provided.
Test in the Android app.

feat: support prompt setup in kotlin sdk

---

android-sdk/android/src/main/kotlin/io/logto/sdk/android/type/LogtoConfig.kt

fix(android-sdk): using persist storage by default
N / A

fix(android-sdk): using persist storage by default

---

kotlin-sdk/kotlin/src/main/kotlin/io/logto/sdk/core/type/IdTokenClaims.kt

fix(android-sdk): role names should only contain not-null string value
UT Passed.

fix(android-sdk): role names should only contain not-null string value

---

kotlin-sdk/kotlin/src/main/kotlin/io/logto/sdk/core/http/HttpRequest.kt

`response.body?.toString()` is returning the `response.body?` instance memory address Example:
```hava
okhttp3.internal.http.RealResponseBody@7cb56da5
```
`response.body?.string()` must be used instead. See https://square.github.io/okhttp/4.x/okhttp/okhttp3/-response-body/string/

fix(core): Fix `ResponseException::responseContent` population

---

android-sdk/android/src/main/kotlin/io/logto/sdk/android/auth/logto/LogtoWebViewAuthActivity.kt
android-sdk/android/src/main/kotlin/io/logto/sdk/android/auth/logto/LogtoWebViewPolyfill.kt
android-sdk/android/src/main/kotlin/io/logto/sdk/android/auth/logto/LogtoWebViewSocialHandler.kt
android-sdk/android/src/test/kotlin/io/logto/sdk/android/auth/logto/LogtoWebViewSocialHandlerTest.kt

feat(android-sdk): support copy text for WebView

feat(android-sdk): support copy text for WebView

---

kotlin-sdk/kotlin/src/main/kotlin/io/logto/sdk/core/type/RefreshTokenTokenResponse.kt

According to [RFC6749](https://datatracker.ietf.org/doc/html/rfc6749#section-6), the server MAY issue a refresh token when refreshing a token, not always.
Note: Since in the previous implementation, the `refreshToken` is used in an optional way, so we can change the type directly.
Test locally.

refactor(core): make `refreshToken` in `RefreshTokenTokenResponse` optional

---

kotlin-sdk/kotlin/src/main/kotlin/io/logto/sdk/core/type/UserInfoResponse.kt
kotlin-sdk/kotlin/src/test/kotlin/io/logto/sdk/core/type/UserInfoResponseTest.kt

Add missing `roles`, `organizations` and `organization roles` fields for user info response data.
Test locally & UT

fix(core): add roles and organization-related data for `userInfoResponse`

---

kotlin-sdk/kotlin/src/main/kotlin/io/logto/sdk/core/Core.kt
kotlin-sdk/kotlin/src/main/kotlin/io/logto/sdk/core/constant/FirstScreen.kt
kotlin-sdk/kotlin/src/main/kotlin/io/logto/sdk/core/constant/Identifier.kt
kotlin-sdk/kotlin/src/main/kotlin/io/logto/sdk/core/constant/QueryKey.kt
kotlin-sdk/kotlin/src/main/kotlin/io/logto/sdk/core/type/GenerateSignInUriOptions.kt
kotlin-sdk/kotlin/src/test/kotlin/io/logto/sdk/core/CoreTest.kt

Add more options for sign-in uri generation in core sdk to align with other SDKs.
These options are used to generate query params in sign-in uri:
- `loginHint`: `login_hint`
- `firstScreen`: `first_screen`
- `identifier`: `identifier`
The `extraParams` option is used to generate extra params in the sing-in uri.
The `includeReservedScopes` option is used to control if the reserved scopes (`openid`, `offline_access` and `profile`) is present in the sign-in uri.
UT and test locally.

feat(core): add more options for sign-in uri generation

---

android-sdk/android/src/main/kotlin/io/logto/sdk/android/auth/logto/LogtoAuthSession.kt
android-sdk/android/src/main/kotlin/io/logto/sdk/android/type/SignInOptions.kt
kotlin-sdk/kotlin/src/main/kotlin/io/logto/sdk/core/Core.kt
kotlin-sdk/kotlin/src/main/kotlin/io/logto/sdk/core/constant/DirectSignInMethod.kt
kotlin-sdk/kotlin/src/main/kotlin/io/logto/sdk/core/type/DirectSignInOptions.kt
kotlin-sdk/kotlin/src/main/kotlin/io/logto/sdk/core/type/GenerateSignInUriOptions.kt
kotlin-sdk/kotlin/src/test/kotlin/io/logto/sdk/core/CoreTest.kt

Support `direct_sign_in` param for sign-in uri
Test locally and all UTs passed.

feat: support `direct_sign_in` param for sign-in uri
