logto-io/kotlin

- android/library/build.gradle
- android/library/src/main/java/io/logto/android/activity/WebViewAuthActivity.kt
- android/library/src/main/java/io/logto/android/authflow/webview/AuthWebViewClient.kt
- android/library/src/main/java/io/logto/android/authflow/webview/WebViewAuthFlow.kt
- android/library/src/main/java/io/logto/android/callback/AuthenticationCallback.kt
- android/library/src/main/java/io/logto/android/callback/AuthorizationCodeCallback.kt
- android/library/src/main/java/io/logto/android/client/LogtoClientBuilder.kt
- android/library/src/main/java/io/logto/android/client/api/LogtoClient.kt
- android/library/src/main/java/io/logto/android/constant/AuthConstant.kt
- android/library/src/main/java/io/logto/android/model/Credential.kt
This pr provide the ability to retrieve credentials
* Implement authentication exceptions according to logto-core ([LOG-80](https://linear.app/silverhand/issue/LOG-80/implement-authentication-exceptions-according-to-logto-core))
> feat: retrieve credentials

- android/library/build.gradle
- android/library/src/main/java/io/logto/android/authflow/webview/WebViewAuthFlow.kt
- android/library/src/main/java/io/logto/android/client/api/LogtoClient.kt
This pr replace retrofit callback with kotlin coroutines
> improvement: use coroutines in project

- android/library/src/main/java/io/logto/android/Logto.kt
- android/library/src/main/java/io/logto/android/activity/WebViewAuthActivity.kt
- android/library/src/main/java/io/logto/android/authflow/webview/WebViewAuthFlow.kt
- android/library/src/main/java/io/logto/android/constant/AuthConstant.kt
- android/library/src/main/java/io/logto/android/storage/CredentialStorage.kt
This pr use SharedPreferences to store credential for future usage
* Clear storage when loging out: [LOG-73](https://linear.app/silverhand/issue/LOG-73/logout)
* Load credential from storage when starting up application: [LOG-70](https://linear.app/silverhand/issue/LOG-70/check-authentication-state)
> feat: store credentials

- android/library/src/main/java/io/logto/android/auth/browser/BrowserFlow.kt
TBD:
* add ci for this project [LOG-140](https://linear.app/silverhand/issue/LOG-140/ci-lint-and-code-style-check)
> fix: incorrect rebase operation

- android/library/src/test/java/io/logto/android/pkce/PkceTest.kt
add related cases from log-io/js to log-io/kotlin
> test: add cases to PkceTest.kt

- android/library/src/main/java/io/logto/android/Logto.kt
- android/library/src/main/java/io/logto/android/auth/browser/BrowserSignInFlow.kt
- android/library/src/main/java/io/logto/android/auth/browser/BrowserSignOutFlow.kt
- android/library/src/main/java/io/logto/android/callback/Callback.kt
- android/library/src/main/java/io/logto/android/client/LogtoAndroidClient.kt
- android/library/src/main/java/io/logto/client/extensions/KtorHttpClientExtensions.kt
- android/library/src/main/java/io/logto/client/service/LogtoService.kt
- android/library/src/test/java/io/logto/android/auth/browser/BrowserSignInFlowTest.kt
- android/library/src/test/java/io/logto/android/auth/browser/BrowserSignOutFlowTest.kt
- android/library/src/test/java/io/logto/android/client/LogtoAndroidClientTest.kt
* Improvement: Better ways to use Kotlin coroutines
* refactor: replace lambda type expression with explicit callback type
* test: align logto coroutine scope with test coroutine scope
* [Improvement: Better ways to use Kotlin coroutines in our Android 3-party library (LOG-192)](https://linear.app/silverhand/issue/LOG-192/improvement-better-ways-to-use-kotlin-coroutines-in-our-android-3)
UT
> Improvement: Better ways to use Kotlin coroutines

- android/library/src/main/java/io/logto/android/Logto.kt
- android/library/src/main/java/io/logto/client/model/TokenSet.kt
- android/library/src/test/java/io/logto/client/utils/PkceUtilsTest.kt
* improvement: remove unused code
* [Remove unused code (LOG-315)](https://linear.app/silverhand/issue/LOG-315/remove-unused-api)
NONE
> improvement: remove unused api

- android/app/src/main/java/io/logto/demo/viewmodel/LogtoViewModel.kt
- android/library/src/main/java/io/logto/android/Logto.kt
* feature: clear local tokenSet once user sign out
* [Align sign out process with js-sdk (xiaoyijun-log-265)](https://linear.app/silverhand/issue/LOG-265/align-sign-out-process-with-js-sdk)
NONE
> feature: clear local tokenSet once user sign out

- android/app/build.gradle
- android/build.gradle
- android/library/build.gradle
* chore: organize sdk library & sample code library
* [organize sdk library & sample code library (LOG-317)](https://linear.app/silverhand/issue/LOG-317/organize-sdk-library-and-sample-code-library)
None
> chore: organize sdk library & sample code library

- .github/workflows/main.yml
improvement: run action on pull request
None
None
> improvement: run action on pull request

- build.gradle.kts
- config/detekt/detekt.yml
- kotlin/build.gradle.kts
* kotlin core SDK: code style lint setup
* LOG-978
None.
> feat(core): code style lint setup

- build.gradle.kts
- settings.gradle.kts
chore: detach old projects
None.
None.
@logto-io/eng
> chore: detach old projects

- build.gradle.kts
- kotlin/build.gradle.kts
setup core SDK's testing env.
* LOG-977
None.
@logto-io/eng
> feat(core): testing env setup

- .github/pull_request_template.md
correct comments in pr template
None.
None.
@logto-io/eng
> chore: correct comments in pr template

- .github/workflows/main.yml
- build.gradle.kts
* ci: check code style
* ci: unit test
* LOG-979
* LOG-981
@logto-io/eng
> feat(core): setup ci for core SDK

- kotlin/src/main/kotlin/io/logto/sdk/core/util/TokenUtils.kt
- kotlin/src/test/kotlin/io/logto/sdk/core/util/TokenUtilsTest.kt
* feat(core): verifyIdToken
* LOG-745
* LOG-988
UT
@logto-io/eng
> feat(core): verifyIdToken

- kotlin/src/main/kotlin/io/logto/sdk/core/Core.kt
- kotlin/src/main/kotlin/io/logto/sdk/core/constant/QueryKey.kt
- kotlin/src/main/kotlin/io/logto/sdk/core/exception/UriConstructionException.kt
- kotlin/src/test/kotlin/io/logto/sdk/core/CoreTest.kt
* feat(core): generateSignOutUri
* LOG-749
UT
@logto-io/eng
> feat(core): generateSignOutUri

- kotlin/src/main/kotlin/io/logto/sdk/core/Core.kt
- kotlin/src/main/kotlin/io/logto/sdk/core/constant/CodeChallengeMethod.kt
- kotlin/src/main/kotlin/io/logto/sdk/core/constant/PromptValue.kt
- kotlin/src/main/kotlin/io/logto/sdk/core/constant/QueryKey.kt
- kotlin/src/main/kotlin/io/logto/sdk/core/constant/ReservedScope.kt
- kotlin/src/main/kotlin/io/logto/sdk/core/constant/ResponseType.kt
- kotlin/src/main/kotlin/io/logto/sdk/core/extension/StringListExt.kt
- kotlin/src/test/kotlin/io/logto/sdk/core/CoreTest.kt
* feat(core): generateSignInUri
* LOG-748
UT
@logto-io/eng
> feat(core): generateSignInUri

- kotlin/src/main/kotlin/io/logto/sdk/core/util/TokenUtils.kt
refactor(core): convert jwt-context to claims directly
None.
UT
@logto-io/eng
> refactor(core): convert jwt-context to claims directly

- android/logto-client/build.gradle.kts
- build.gradle.kts
ci: setup test & code style check for android sdk
None.
None.
> feat(android): test & code style check ci setup

- android/logto-client/build.gradle.kts
- android/logto-client/src/main/kotlin/io/logto/sdk/android/type/AccessToken.kt
- android/logto-client/src/main/kotlin/io/logto/sdk/android/type/LogtoConfig.kt
- android/logto-client/src/test/kotlin/io/logto/sdk/android/type/LogtoConfigTest.kt
- android/settings.gradle.kts
* AccessToken
* LogtoConfig
* LOG-1122
* LOG-1121
UT
> feat(android): android basic type

- kotlin/src/main/kotlin/io/logto/sdk/core/util/CallbackUriUtils.kt
- kotlin/src/test/kotlin/io/logto/sdk/core/util/CallbackUriUtilsTest.kt
* refactor(core): rename `UriUtils` to `CallbackUriUtils`
* [Disscussion in Slack](https://silverhand-io.slack.com/archives/C02A8G4HVAM/p1643099629269600)
None.
UT
@logto-io/eng
> refactor(core): rename `UriUtils` to `CallbackUriUtils`

- android/logto-client/src/main/kotlin/io/logto/sdk/android/LogtoClient.kt
feat(android): nit logto client
* LOG-1097
* LOG-1095
* LOG-1096
UT
> feat(android): init logto client

- android/logto-client/src/main/kotlin/io/logto/sdk/android/type/LogtoConfig.kt
- kotlin/src/main/kotlin/io/logto/sdk/core/Core.kt
- kotlin/src/main/kotlin/io/logto/sdk/core/extension/StringListExt.kt
- kotlin/src/main/kotlin/io/logto/sdk/core/util/ScopeUtils.kt
- kotlin/src/test/kotlin/io/logto/sdk/core/util/ScopeUtilsTest.kt
refactor(core): refactor `StringListExt` to `ScopeUtils`
* LOG-1420
UT
> refactor(core): refactor `StringListExt` to `ScopeUtils`

- android/logto-client/build.gradle.kts
- android/logto-client/src/main/kotlin/io/logto/sdk/android/LogtoClient.kt
- android/logto-client/src/main/kotlin/io/logto/sdk/android/callback/RetrieveCallback.kt
- android/logto-client/src/main/kotlin/io/logto/sdk/android/extension/LogtoConfigExt.kt
- android/logto-client/src/test/kotlin/io/logto/sdk/android/LogtoClientTest.kt
- android/logto-client/src/test/resources/logback.xml
feat(android): private method `getOidcConfig`
* LOG-1429
UT
> feat(android): private method `getOidcConfig`

- .github/workflows/main.yml
ci: change the executing time of main action
None.
None.
> ci: change the executing time of main action

- android/logto-client/src/main/kotlin/io/logto/sdk/android/LogtoClient.kt
- android/logto-client/src/test/kotlin/io/logto/sdk/android/LogtoClientTest.kt
- kotlin/src/main/kotlin/io/logto/sdk/core/Core.kt
- kotlin/src/test/kotlin/io/logto/sdk/core/CoreFetchTest.kt
refactor(core): correct function name `fetchOidcConfig`
None.
UT
> refactor(core): correct function name `fetchOidcConfig`

- .github/workflows/add-labels.yml
> ci: add labels

- kotlin/src/main/kotlin/io/logto/sdk/core/exception/ResponseException.kt
- kotlin/src/main/kotlin/io/logto/sdk/core/http/HttpRequest.kt
feat(core): add empty response exception to http module
None.
UT
> feat(core): add empty response exception to http module

- kotlin/src/test/kotlin/io/logto/sdk/core/util/TokenUtilsTest.kt
Add a bigger delta time to the expiration test to avoid ut falling accidentally.
None.
UT
> chore(core): add a bigger delta time to expiration test

- kotlin/src/main/kotlin/io/logto/sdk/core/Core.kt
- kotlin/src/test/kotlin/io/logto/sdk/core/CoreFetchTest.kt
fix(core): use not nullable in `HttpCompletion`
None.
UT
> fix(core): use not nullable in `HttpCompletion`

- kotlin/src/main/kotlin/io/logto/sdk/core/type/OidcConfigResponse.kt
- kotlin/src/test/kotlin/io/logto/sdk/core/CoreFetchTest.kt
feat(core): add `userinfoEndpoint` to `OidcConfigResponse`
None.
UT
> feat(core): add `userinfoEndpoint` to `OidcConfigResponse`

- android/logto-client/src/main/kotlin/io/logto/sdk/android/extension/LogtoConfigExt.kt
- android/logto-client/src/test/kotlin/io/logto/sdk/android/LogtoClientTest.kt
refactor(android): append `/oidc` for `oidcConfigEndpoint`
* LOG-1432
UT
> refactor(android): append `/oidc` for `oidcConfigEndpoint`

- android/logto-client/src/main/kotlin/io/logto/sdk/android/LogtoClient.kt
- android/logto-client/src/main/kotlin/io/logto/sdk/android/exception/LogtoException.kt
- android/logto-client/src/main/kotlin/io/logto/sdk/android/util/LogtoUtils.kt
- android/logto-client/src/test/kotlin/io/logto/sdk/android/LogtoClientTest.kt
- android/logto-client/src/test/resources/logback.xml
feat(android): getAccessToken
* LOG-1100
UT
> feat(android): getAccessToken

- android/logto-client/src/main/kotlin/io/logto/sdk/android/LogtoClient.kt
- android/logto-client/src/main/kotlin/io/logto/sdk/android/callback/RetrieveCallback.kt
- android/logto-client/src/test/kotlin/io/logto/sdk/android/LogtoClientTest.kt
- kotlin/src/main/kotlin/io/logto/sdk/core/http/HttpCompletion.kt
- kotlin/src/test/kotlin/io/logto/sdk/core/CoreFetchTest.kt
There is a problem with SAM usage in kotlin. reference: [kotlin_for_java_consumption](https://developer.android.com/kotlin/interop#kotlin_for_java_consumption)
But [`fun interface`](https://kotlinlang.org/docs/fun-interfaces.html#functional-interfaces-vs-type-aliases) solves this problem.
* LOG-1453
UT
> refactor: change `interface` to `fun interface`

- android/logto-client/src/main/kotlin/io/logto/sdk/android/LogtoClient.kt
- android/logto-client/src/test/kotlin/io/logto/sdk/android/LogtoClientTest.kt
- kotlin/build.gradle.kts
feat(android): getIdTokenClaims
* LOG-1101
UT
> feat(android): getIdTokenClaims

- android/logto-client/src/test/kotlin/io/logto/sdk/android/LogtoClientTest.kt
refactor(android): use lambda exp in `getIdTokenClaims`' ut
None.
UT
> refactor(android): use lambda exp in `getIdTokenClaims`' ut

- android/logto-client/src/main/kotlin/io/logto/sdk/android/LogtoClient.kt
- android/logto-client/src/test/kotlin/io/logto/sdk/android/LogtoClientTest.kt
feat(android): fetchUserInfo
* LOG-1102
UT
> feat(android): fetchUserInfo

- android-sdk/android/src/main/kotlin/io/logto/sdk/android/LogtoClient.kt
- android-sdk/android/src/main/kotlin/io/logto/sdk/android/type/LogtoConfig.kt
- android-sdk/android/src/test/kotlin/io/logto/sdk/android/LogtoClientTest.kt
- android-sdk/android/src/test/kotlin/io/logto/sdk/android/type/LogtoConfigTest.kt
- kotlin-sdk/kotlin/src/main/kotlin/io/logto/sdk/core/Core.kt
- kotlin-sdk/kotlin/src/main/kotlin/io/logto/sdk/core/util/ScopeUtils.kt
- kotlin-sdk/kotlin/src/test/kotlin/io/logto/sdk/core/CoreFetchTest.kt
- kotlin-sdk/kotlin/src/test/kotlin/io/logto/sdk/core/CoreTest.kt
- kotlin-sdk/kotlin/src/test/kotlin/io/logto/sdk/core/util/ScopeUtilsTest.kt
* rename `withDefaultScopes` to `withReservedScopes`
* update naming to `resources` and `scopes`
None.
UT
> refactor: update naming about `resources` and `scopes`

- android-sdk/android/src/main/kotlin/io/logto/sdk/android/LogtoClient.kt
- config/detekt/detekt.yml
improvement: disable `TooManyFunctions` rule
* LOG-1454
UT
> improvement: disable `TooManyFunctions` rule

- android-sample/app/src/main/java/io/logto/demo/fragment/LoginFragment.kt
- android-sample/app/src/main/res/values/logto.xml
- android-sdk/android/build.gradle.kts
- android-sdk/android/src/main/AndroidManifest.xml
- android-sdk/android/src/main/kotlin/io/logto/sdk/android/LogtoClient.kt
- android-sdk/android/src/main/kotlin/io/logto/sdk/android/auth/activity/CallbackUriActivity.kt
- android-sdk/android/src/main/kotlin/io/logto/sdk/android/auth/activity/SignInActivity.kt
- android-sdk/android/src/main/kotlin/io/logto/sdk/android/auth/session/SignInSession.kt
- android-sdk/android/src/main/kotlin/io/logto/sdk/android/auth/session/SignInSessionManager.kt
- android-sdk/android/src/main/kotlin/io/logto/sdk/android/callback/Completion.kt
- android-sdk/android/src/main/kotlin/io/logto/sdk/android/exception/LogtoException.kt
- android-sdk/android/src/main/res/values/logto.xml
- android-sdk/gradle.properties
- kotlin-sdk/kotlin/src/main/kotlin/io/logto/sdk/core/constant/QueryKey.kt
This feature is split into two parts:
* get authorization code
* fetch token by authorization code
This PR is part one: get authorization code.
Todo: Refactor Completion
* LOG-1098
Success:
Cancel:
> feat(android): signInWithBrowser - get authorization code

- kotlin-sdk/kotlin/src/main/kotlin/io/logto/sdk/core/util/CallbackUriUtils.kt
- kotlin-sdk/kotlin/src/test/kotlin/io/logto/sdk/core/util/CallbackUriUtilsTest.kt
fix(core): support custom scheme in verifyAndParseCodeFromCallbackUri
TODO: LOG-1487: Replace HttpUrl with More Suitable Utils
None.
UT
> fix(core): support custom scheme in verifyAndParseCodeFromCallbackUri

- kotlin-sdk/kotlin/src/main/kotlin/io/logto/sdk/core/Core.kt
- kotlin-sdk/kotlin/src/main/kotlin/io/logto/sdk/core/constant/MediaType.kt
fix: should post `application/x-www-form-urlencoded` in a correct way.
None.
Before: Can't not get param in the server side
After: Worked!
> fix(core): post with form body

- kotlin-sdk/kotlin/src/main/kotlin/io/logto/sdk/core/util/GenerateUtils.kt
- kotlin-sdk/kotlin/src/test/kotlin/io/logto/sdk/core/util/GenerateUtilsTest.kt
> fix(core): generateRandomString

- android-sdk/android/src/main/kotlin/io/logto/sdk/android/LogtoClient.kt
- android-sdk/android/src/main/kotlin/io/logto/sdk/android/auth/session/SignInSession.kt
feat(anroid): signInWithBrowser - fetch token
* LOG-1489: Refactor: LogtoCompletion
* LOG-1112: Storage
* LOG-537: Exception
* LOG-1098
fetch access token successfully
> feat(anroid): signInWithBrowser - fetch token

- android-sample/app/src/main/java/io/logto/demo/fragment/LoginFragment.kt
- android-sdk/android/src/main/kotlin/io/logto/sdk/android/LogtoClient.kt
- android-sdk/android/src/main/kotlin/io/logto/sdk/android/callback/Completion.kt
- kotlin-sdk/kotlin/src/main/kotlin/io/logto/sdk/core/http/HttpCompletion.kt
- kotlin-sdk/kotlin/src/main/kotlin/io/logto/sdk/core/http/HttpGet.kt
- kotlin-sdk/kotlin/src/main/kotlin/io/logto/sdk/core/http/HttpPost.kt
- kotlin-sdk/kotlin/src/main/kotlin/io/logto/sdk/core/http/HttpRequest.kt
* refactor: completion
* add bound to generic type
* LOG-537: Exceptions
* LOG-1489
UT & Test in App
> refactor: completion

- android-sdk/android/src/main/kotlin/io/logto/sdk/android/LogtoClient.kt
feat(android): signOut
Align with swift SDK currently.
Need to redirect to `endSessionEndpoint` in the future (LOG-1496)
* LOG-1474 : Research: Sign out on endSessionEndpoint
* LOG-1112:  Storage
* LOG-537: Exception
* LOG-1496: Redirect to `EndSessionEndpoint` on Sign Out
* LOG-1099
Test in App
1. Sign in
2. Get `idTokenCliams` successfully
3. Sign out
4. Get `idTokenClaims` unsuccessfully
> feat(android): sign out

- android-sample/app/build.gradle.kts
- android-sample/app/src/main/java/io/logto/demo/MainActivity.kt
- android-sample/app/src/main/java/io/logto/demo/fragment/LoginFragment.kt
- android-sample/app/src/main/java/io/logto/demo/fragment/TokenFragment.kt
- android-sample/app/src/main/java/io/logto/demo/viewmodel/LogtoViewModel.kt
- android-sample/app/src/main/java/io/logto/demo/viewmodel/LogtoViewModelFactory.kt
kotlin sample
* Sign out example
* Storage example
* LOG-1091
> feat: kotlin sample

- android-sample/app/src/main/java/io/logto/demo/fragment/TokenFragment.kt
- android-sample/app/src/main/java/io/logto/demo/viewmodel/LogtoViewModel.kt
Prerequisite of storage devempment & test
* LOG-1112
None.
> feat(sample): kotlin sample - signout

- .github/workflows/main.yml
- android-sdk/android/build.gradle.kts
- build.gradle.kts
ci(android): android lint
* LOG-1085
Github Actions
> ci(android): android lint

- android-sample/app/src/main/java/io/logto/demo/viewmodel/LogtoViewModel.kt
- android-sdk/android/src/main/kotlin/io/logto/sdk/android/LogtoClient.kt
- android-sdk/android/src/main/kotlin/io/logto/sdk/android/constant/StorageKey.kt
- android-sdk/android/src/main/kotlin/io/logto/sdk/android/storage/PersistStorage.kt
- android-sdk/android/src/test/kotlin/io/logto/sdk/android/LogtoClientTest.kt
feat(android): storage
* LOG-1112
Test in App:
1. sign in and restart: should have stored data:
2. sign out and restart: stored data should be cleared:
> feat(android): storage

- android-sdk/android/src/main/kotlin/io/logto/sdk/android/LogtoClient.kt
- android-sdk/android/src/main/kotlin/io/logto/sdk/android/exception/LogtoException.kt
- android-sdk/android/src/test/kotlin/io/logto/sdk/android/LogtoClientTest.kt
- kotlin-sdk/kotlin/src/main/kotlin/io/logto/sdk/core/http/HttpRequest.kt
feat: verify token response
* LOG-1483
UT & Test In App
> feat: verify token response

- android-sdk/android/src/main/kotlin/io/logto/sdk/android/LogtoClient.kt
- kotlin-sdk/kotlin/src/main/kotlin/io/logto/sdk/core/http/HttpCompletion.kt
- kotlin-sdk/kotlin/src/main/kotlin/io/logto/sdk/core/http/HttpGet.kt
- kotlin-sdk/kotlin/src/main/kotlin/io/logto/sdk/core/http/HttpPost.kt
- kotlin-sdk/kotlin/src/main/kotlin/io/logto/sdk/core/http/HttpRequest.kt
feat(core): support request for raw string
* LOG-1518
UT & Test In App
> feat(core): support request for raw string

- .github/workflows/main.yml
- .gitignore
- android-sdk/android/build.gradle.kts
- kotlin-sdk/kotlin/build.gradle.kts
Init codecov github actions to upload the test report
LOG-732
> ci(kotlin): add codecov github actions

- .github/workflows/main.yml
- android-sdk/android/build.gradle.kts
- build.gradle.kts
- kotlin-sdk/kotlin/build.gradle.kts
update kotlin and android sdk code coverage task
Replace jacco with kover plugin
Create the koverReport task to run the task and generate code coverage reports
run task locally
@xiaoyijun cc: @logto-io/eng
> test(ci): update kotlin and android sdk code coverage task

- android-sdk/android/src/main/kotlin/io/logto/sdk/android/LogtoClient.kt
Fetch token by refresh token should handle concurrent requests with the same refresh token
* LOG-1902
UT & Test in the sample app
> feat(android-sdk): suspend concurrent token refresh request

- android-sdk/android/src/main/kotlin/io/logto/sdk/android/LogtoClient.kt
- android-sdk/android/src/main/kotlin/io/logto/sdk/android/auth/logto/LogtoAuthSession.kt
- android-sdk/android/src/main/kotlin/io/logto/sdk/android/auth/logto/LogtoWebViewSocialHandler.kt
- android-sdk/android/src/main/kotlin/io/logto/sdk/android/auth/social/SocialException.kt
- android-sdk/android/src/main/kotlin/io/logto/sdk/android/auth/social/SocialSession.kt
- android-sdk/android/src/main/kotlin/io/logto/sdk/android/auth/social/SocialSessionHelper.kt
- android-sdk/android/src/main/kotlin/io/logto/sdk/android/auth/social/alipay/AlipaySocialSession.kt
- android-sdk/android/src/main/kotlin/io/logto/sdk/android/auth/social/web/WebSocialSession.kt
- android-sdk/android/src/main/kotlin/io/logto/sdk/android/auth/social/wechat/WechatSocialSession.kt
- android-sdk/android/src/main/kotlin/io/logto/sdk/android/completion/Completion.kt
- android-sdk/android/src/test/kotlin/io/logto/sdk/android/LogtoClientTest.kt
* feat(android-sdk): handle social error
* refactor `Completion` interface to receive a generic type for exceptions.
Implemented according to https://www.notion.so/silverhand/Social-Errors-94f8499b728947fa8309267f69a7d7c5
* LOG-2186
Test in sample app.
> feat(android-sdk): handle social error

- android-sdk/android/src/main/kotlin/io/logto/sdk/android/auth/logto/LogtoWebViewSocialHandler.kt
feat(android-sdk): align callback uri scheme
per slack disscussion: https://silverhand-io.slack.com/archives/C02A8G4HVAM/p1650343181926779
None.
No need.
> feat(android-sdk): align callback uri scheme

- android-sdk/android/build.gradle.kts
- android-sdk/android/src/main/kotlin/io/logto/sdk/android/auth/logto/LogtoWebViewAuthActivity.kt
- android-sdk/android/src/test/kotlin/io/logto/sdk/android/auth/logto/LogtoWebViewAuthActivityTest.kt
- gradle/libs.versions.toml
test(android-sdk): add ut for logto webview auth activity
* LOG-2226
UT
> test(android-sdk): add ut for logto webview auth activity

- android-sdk/android/src/main/kotlin/io/logto/sdk/android/auth/logto/LogtoWebViewSocialHandler.kt
- android-sdk/android/src/test/kotlin/io/logto/sdk/android/auth/logto/LogtoWebViewSocialHandlerTest.kt
test(android-sdk): post social exception
* LOG-2226
UT
> test(android-sdk): post social exception

- android-sdk/android/src/main/kotlin/io/logto/sdk/android/auth/logto/LogtoWebViewAuthClient.kt
- android-sdk/android/src/test/kotlin/io/logto/sdk/android/auth/logto/LogtoWebViewAuthClientTest.kt
test(android-sdk): add ut for logtoWebviewAuthClient
* LOG-2226
UT
> test(android-sdk): add ut for logto webview auth client

- android-sdk/android/src/main/kotlin/io/logto/sdk/android/auth/social/web/WebSocialResultActivity.kt
- android-sdk/android/src/test/kotlin/io/logto/sdk/android/auth/social/web/WebSocialResultActivityTest.kt
test(android-sdk): web social result activity
* LOG-2226
UT
> test(android-sdk): web social result activity

- android-sdk/android/build.gradle.kts
- android-sdk/android/src/main/kotlin/io/logto/sdk/android/auth/social/wechat/WechatSocialResultActivity.kt
- android-sdk/android/src/test/kotlin/io/logto/sdk/android/auth/social/wechat/WechatSocialResultActivityTest.kt
test(android-sdk): wechat social result activity
* LOG-2226
UT
> test(android-sdk): wechat social result activity

- android-sdk/android/src/main/kotlin/io/logto/sdk/android/LogtoClient.kt
- android-sdk/android/src/test/kotlin/io/logto/sdk/android/LogtoClientTest.kt
- kotlin-sdk/kotlin/src/main/kotlin/io/logto/sdk/core/Core.kt
- kotlin-sdk/kotlin/src/test/kotlin/io/logto/sdk/core/CoreFetchTest.kt
* feat(core): fetch jwks json
* adjust time bias to 10 to avoid unexpect result when running tests
* rename some unit tests names
N/A
UT
> feat(core): fetch jwks json

- android-sdk/android/src/main/kotlin/io/logto/sdk/android/LogtoClient.kt
- android-sdk/android/src/test/kotlin/io/logto/sdk/android/LogtoClientTest.kt
test(android-sdk): logto client
* LOG-2226
UT
> test(android-sdk): logto client

- android-sample-kotlin/app/src/main/kotlin/io/logto/android/sample4k/viewmodel/LogtoViewModel.kt
- android-sdk/android/src/main/kotlin/io/logto/sdk/android/LogtoClient.kt
- android-sdk/android/src/main/kotlin/io/logto/sdk/android/auth/logto/LogtoAuthSession.kt
- android-sdk/android/src/main/kotlin/io/logto/sdk/android/type/LogtoConfig.kt
- android-sdk/android/src/test/kotlin/io/logto/sdk/android/LogtoClientTest.kt
- android-sdk/android/src/test/kotlin/io/logto/sdk/android/auth/logto/LogtoAuthSessionTest.kt
- android-sdk/android/src/test/kotlin/io/logto/sdk/android/extension/LogtoConfigExtKtTest.kt
- android-sdk/android/src/test/kotlin/io/logto/sdk/android/type/LogtoConfigTest.kt
refactor(android-sdk): `clientId` -> `appId`
* LOG-2250
UT
> refactor(android-sdk): `clientId` -> `appId`

- android-sdk/android/src/main/kotlin/io/logto/sdk/android/LogtoClient.kt
- build-logic/detekt/src/main/resources/detekt.yml
- kotlin-sdk/kotlin/src/main/kotlin/io/logto/sdk/core/Core.kt
feat: suppress long params list style check
N/A
CI
> feat: suppress long params list style check

- kotlin-sdk/kotlin/build.gradle.kts
feat(core): deploy core sdk
Requirements if we want to deploy to the Maven Central: https://central.sonatype.org/publish/requirements/
Config target remote repo URL when it is ready.
Contents to be publish:
> feat(core): deployment

- android-sdk/android/src/test/kotlin/io/logto/sdk/android/auth/logto/LogtoAuthManagerTest.kt
- android-sdk/android/src/test/kotlin/io/logto/sdk/android/auth/logto/LogtoAuthSessionTest.kt
- android-sdk/android/src/test/kotlin/io/logto/sdk/android/auth/logto/LogtoWebViewAuthClientTest.kt
- android-sdk/android/src/test/kotlin/io/logto/sdk/android/auth/logto/LogtoWebViewSocialHandlerTest.kt
- android-sdk/android/src/test/kotlin/io/logto/sdk/android/auth/social/SocialSessionHelperTest.kt
- android-sdk/android/src/test/kotlin/io/logto/sdk/android/auth/social/alipay/AlipaySocialSessionTest.kt
- android-sdk/android/src/test/kotlin/io/logto/sdk/android/auth/social/web/WebSocialSessionTest.kt
- android-sdk/android/src/test/kotlin/io/logto/sdk/android/auth/social/wechat/WechatSocialResultActivityTest.kt
- android-sdk/android/src/test/kotlin/io/logto/sdk/android/auth/social/wechat/WechatSocialSessionTest.kt
- android-sdk/android/src/test/kotlin/io/logto/sdk/android/type/AccessTokenTest.kt
- android-sdk/android/src/test/kotlin/io/logto/sdk/android/util/LogtoUtilsTest.kt
- kotlin-sdk/kotlin/src/test/kotlin/io/logto/sdk/core/CoreFetchTest.kt
- kotlin-sdk/kotlin/src/test/kotlin/io/logto/sdk/core/CoreTest.kt
- kotlin-sdk/kotlin/src/test/kotlin/io/logto/sdk/core/extension/JwtClaimsExtKtTest.kt
- kotlin-sdk/kotlin/src/test/kotlin/io/logto/sdk/core/type/CodeTokenResponseTest.kt
- kotlin-sdk/kotlin/src/test/kotlin/io/logto/sdk/core/type/IdTokenClaimsTest.kt
- kotlin-sdk/kotlin/src/test/kotlin/io/logto/sdk/core/type/OidcConfigResponseTest.kt
- kotlin-sdk/kotlin/src/test/kotlin/io/logto/sdk/core/type/RefreshTokenTokenResponseTest.kt
- kotlin-sdk/kotlin/src/test/kotlin/io/logto/sdk/core/type/UserInfoResponseTest.kt
- kotlin-sdk/kotlin/src/test/kotlin/io/logto/sdk/core/util/CallbackUriUtilsTest.kt
- kotlin-sdk/kotlin/src/test/kotlin/io/logto/sdk/core/util/GenerateUtilsTest.kt
- kotlin-sdk/kotlin/src/test/kotlin/io/logto/sdk/core/util/TokenUtilsTest.kt
refactor: align test description
LOG-2269
UT
> refactor: align test description

- android-sdk/android/build.gradle.kts
- kotlin-sdk/kotlin/build.gradle.kts
feat(android-sdk): deployment
* LOG-446
Include all required files in publish result folder:
> feat(android-sdk): deployment

- android-sdk/android/src/main/kotlin/io/logto/sdk/android/LogtoClient.kt
- android-sdk/android/src/main/kotlin/io/logto/sdk/android/auth/logto/LogtoAuthSession.kt
- android-sdk/android/src/main/kotlin/io/logto/sdk/android/exception/LogtoException.kt
- android-sdk/android/src/test/kotlin/io/logto/sdk/android/LogtoClientTest.kt
- android-sdk/android/src/test/kotlin/io/logto/sdk/android/auth/logto/LogtoAuthSessionTest.kt
- kotlin-sdk/kotlin/src/main/kotlin/io/logto/sdk/core/Core.kt
- kotlin-sdk/kotlin/src/main/kotlin/io/logto/sdk/core/exception/CallbackUriVerificationException.kt
- kotlin-sdk/kotlin/src/main/kotlin/io/logto/sdk/core/exception/ResponseException.kt
- kotlin-sdk/kotlin/src/main/kotlin/io/logto/sdk/core/exception/UriConstructionException.kt
- kotlin-sdk/kotlin/src/main/kotlin/io/logto/sdk/core/http/HttpGet.kt
- kotlin-sdk/kotlin/src/main/kotlin/io/logto/sdk/core/http/HttpPost.kt
- kotlin-sdk/kotlin/src/main/kotlin/io/logto/sdk/core/http/HttpRequest.kt
- kotlin-sdk/kotlin/src/main/kotlin/io/logto/sdk/core/util/CallbackUriUtils.kt
- kotlin-sdk/kotlin/src/test/kotlin/io/logto/sdk/core/CoreTest.kt
- kotlin-sdk/kotlin/src/test/kotlin/io/logto/sdk/core/util/CallbackUriUtilsTest.kt
* rename exception `Message` to `Type`
* remove redundant `Enum<*>` in exception classes.
N/A
UT
> refactor: exceptions

- build-logic/settings.gradle.kts
chore: remove reduplicate repository declaration
N/A
CI
> chore: remove reduplicate repository declaration

- android-sdk/android/src/main/kotlin/io/logto/sdk/android/LogtoClient.kt
- kotlin-sdk/kotlin/src/main/kotlin/io/logto/sdk/core/util/CallbackUriUtils.kt
- kotlin-sdk/kotlin/src/main/kotlin/io/logto/sdk/core/util/ScopeUtils.kt
- kotlin-sdk/kotlin/src/main/kotlin/io/logto/sdk/core/util/TokenUtils.kt
* docs: logto core utils
N/A
Test in the doc page.
> docs: logto core utils

- android-sdk/android/src/main/kotlin/io/logto/sdk/android/auth/logto/LogtoWebViewSocialHandler.kt
- android-sdk/android/src/main/kotlin/io/logto/sdk/android/auth/social/SocialSessionHelper.kt
- android-sdk/android/src/main/kotlin/io/logto/sdk/android/auth/social/alipay/AlipaySocialSession.kt
- android-sdk/android/src/main/kotlin/io/logto/sdk/android/auth/social/wechat/WechatSocialSession.kt
- android-sdk/android/src/test/kotlin/io/logto/sdk/android/auth/logto/LogtoWebViewSocialHandlerTest.kt
- android-sdk/android/src/test/kotlin/io/logto/sdk/android/auth/social/SocialSessionHelperTest.kt
* rename `connector id` -> `connector target` and `callback scheme` -> `callback link`
* align connector target names with core
* LOG-2551
UT
> refactor(android-sdk): `connector id` -> `connector target` and `callback scheme` -> `callback link`

- android-sdk/android/src/main/AndroidManifest.xml
* fix(android-sdk): navigate to alipay app in android 11
N/A
Test in real app.
> fix(android-sdk): navigate to alipay app in android 11

- android-sdk/android/src/main/kotlin/io/logto/sdk/android/auth/logto/LogtoWebViewSocialHandler.kt
- android-sdk/android/src/main/kotlin/io/logto/sdk/android/auth/social/SocialSessionHelper.kt
- android-sdk/android/src/test/kotlin/io/logto/sdk/android/auth/logto/LogtoWebViewSocialHandlerTest.kt
- android-sdk/android/src/test/kotlin/io/logto/sdk/android/auth/social/SocialSessionHelperTest.kt
update native and logto ui convention according to this [slack disscussion](https://silverhand-io.slack.com/archives/C02A8G4HVAM/p1652930136707569).
N/A
UT
> feat(android-sdk): update native and logto ui convention

- android-sdk/android/src/main/kotlin/io/logto/sdk/android/auth/social/alipay/AlipaySocialSession.kt
- android-sdk/android/src/main/kotlin/io/logto/sdk/android/auth/social/wechat/WechatSocialResultActivity.kt
- android-sdk/android/src/main/kotlin/io/logto/sdk/android/auth/social/wechat/WechatSocialSession.kt
- android-sdk/android/src/test/kotlin/io/logto/sdk/android/auth/social/alipay/AlipaySocialSessionTest.kt
- android-sdk/android/src/test/kotlin/io/logto/sdk/android/auth/social/wechat/WechatSocialResultActivityTest.kt
- android-sdk/android/src/test/kotlin/io/logto/sdk/android/auth/social/wechat/WechatSocialSessionTest.kt
fix(android-sdk): native social auth state
Reference to https://silverhand-io.slack.com/archives/C02A8G4HVAM/p1653272971878809
N/A
UT
> fix(android-sdk): native social auth state

- android-sdk/android/src/main/kotlin/io/logto/sdk/android/auth/social/alipay/AlipaySocialSession.kt
- android-sdk/android/src/test/kotlin/io/logto/sdk/android/auth/social/alipay/AlipaySocialSessionTest.kt
feat(android-sdk): forward all alipay auth results
N/A
UT & Test in demo app
> feat(android-sdk): forward all alipay auth results

- android-sdk/android/src/test/kotlin/io/logto/sdk/android/type/LogtoConfigTest.kt
- kotlin-sdk/kotlin/src/main/kotlin/io/logto/sdk/core/constant/ReservedScope.kt
- kotlin-sdk/kotlin/src/main/kotlin/io/logto/sdk/core/util/ScopeUtils.kt
- kotlin-sdk/kotlin/src/test/kotlin/io/logto/sdk/core/CoreTest.kt
- kotlin-sdk/kotlin/src/test/kotlin/io/logto/sdk/core/util/ScopeUtilsTest.kt
add `profile` to reserved scopes
N/A
UT
> feat(core): add profile scope

- android-sdk/android/build.gradle.kts
> chore(android-sdk): fix idents

- .github/workflows/commitlint.yml
> ci: add commit lint

- android-sdk/android/src/main/kotlin/io/logto/sdk/android/LogtoClient.kt
- android-sdk/android/src/main/kotlin/io/logto/sdk/android/type/LogtoConfig.kt
- android-sdk/android/src/test/kotlin/io/logto/sdk/android/LogtoClientTest.kt
- android-sdk/android/src/test/kotlin/io/logto/sdk/android/auth/logto/LogtoAuthSessionTest.kt
- android-sdk/android/src/test/kotlin/io/logto/sdk/android/type/LogtoConfigTest.kt
- kotlin-sdk/kotlin/src/main/kotlin/io/logto/sdk/core/Core.kt
- kotlin-sdk/kotlin/src/main/kotlin/io/logto/sdk/core/constant/ClaimName.kt
- kotlin-sdk/kotlin/src/main/kotlin/io/logto/sdk/core/constant/PreservedScope.kt
- kotlin-sdk/kotlin/src/main/kotlin/io/logto/sdk/core/constant/ReservedScope.kt
- kotlin-sdk/kotlin/src/main/kotlin/io/logto/sdk/core/constant/UserScope.kt
- kotlin-sdk/kotlin/src/main/kotlin/io/logto/sdk/core/extension/JwtClaimsExt.kt
- kotlin-sdk/kotlin/src/main/kotlin/io/logto/sdk/core/type/OidcConfigResponse.kt
- kotlin-sdk/kotlin/src/main/kotlin/io/logto/sdk/core/type/UserInfoResponse.kt
- kotlin-sdk/kotlin/src/main/kotlin/io/logto/sdk/core/util/ScopeUtils.kt
- kotlin-sdk/kotlin/src/test/kotlin/io/logto/sdk/core/CoreFetchTest.kt
- kotlin-sdk/kotlin/src/test/kotlin/io/logto/sdk/core/CoreTest.kt
- kotlin-sdk/kotlin/src/test/kotlin/io/logto/sdk/core/constant/ConstantTest.kt
- kotlin-sdk/kotlin/src/test/kotlin/io/logto/sdk/core/extension/JwtClaimsExtKtTest.kt
- kotlin-sdk/kotlin/src/test/kotlin/io/logto/sdk/core/type/IdTokenClaimsTest.kt
- kotlin-sdk/kotlin/src/test/kotlin/io/logto/sdk/core/type/OidcConfigResponseTest.kt
- kotlin-sdk/kotlin/src/test/kotlin/io/logto/sdk/core/type/UserInfoResponseTest.kt
- kotlin-sdk/kotlin/src/test/kotlin/io/logto/sdk/core/util/ScopeUtilsTest.kt
- feat: fetch user info
- rename `ReservedScope` -> `PreservedScope`
- add `UserScope`
- rename `withReservedScopes` -> `withDefaultScopes`
UT & Tested in the Android sample
> feat: fetch user info

- gradle/logto.versions.toml
chore: update build version to `1.0.0-alpha.1`
No need.
> chore: update build version to `1.0.0-alpha.1`

- android-sdk/android/src/main/kotlin/io/logto/sdk/android/LogtoClient.kt
remove refresh token concurrent request protection. For now, we protect it on the server side.
UT Passed & Test locally.
> refactor(android-sdk): remove refresh token concurrent request protection

- gradle/logto.versions.toml
chore: update build version to `1.0.0-alpha.2`
None.
> chore: update build version to `1.0.0-alpha.2`

- gradle/logto.versions.toml
chore: update build version to `1.0.0-alpha.3`
None.
> chore: update build version to `1.0.0-alpha.3`

- android-sdk/android/src/main/kotlin/io/logto/sdk/android/LogtoClient.kt
Remove the parameter scope for getAccessTokenByRefreshToken. Then the OP server will automatically attach all the available scopes (in refresh token) to this access token.
Test locally.
> feat(android-sdk): remove scope for access token grant

- gradle/logto.versions.toml
chore: update build version to `1.0.0-rc.0`
NA
> chore: update build version to `1.0.0-rc.0`

- kotlin-sdk/kotlin/src/main/kotlin/io/logto/sdk/core/constant/ClaimName.kt
- kotlin-sdk/kotlin/src/main/kotlin/io/logto/sdk/core/extension/JwtClaimsExt.kt
- kotlin-sdk/kotlin/src/main/kotlin/io/logto/sdk/core/type/IdTokenClaims.kt
- kotlin-sdk/kotlin/src/main/kotlin/io/logto/sdk/core/type/UserInfoResponse.kt
- kotlin-sdk/kotlin/src/test/kotlin/io/logto/sdk/core/CoreFetchTest.kt
- kotlin-sdk/kotlin/src/test/kotlin/io/logto/sdk/core/extension/JwtClaimsExtKtTest.kt
- kotlin-sdk/kotlin/src/test/kotlin/io/logto/sdk/core/type/IdTokenClaimsTest.kt
- kotlin-sdk/kotlin/src/test/kotlin/io/logto/sdk/core/type/UserInfoResponseTest.kt
refactor(core): remove deprecated role names
UT
> refactor(core): remove deprecated role names

- kotlin-sdk/kotlin/src/main/kotlin/io/logto/sdk/core/Core.kt
- kotlin-sdk/kotlin/src/main/kotlin/io/logto/sdk/core/constant/QueryKey.kt
- kotlin-sdk/kotlin/src/test/kotlin/io/logto/sdk/core/CoreTest.kt
refactor(core): replace `idTokenHint` with `clientId` in sign-out url
UT & Test locally.
> refactor(core): replace `idTokenHint` with `clientId` in sign-out url

- gradle/logto.versions.toml
chore: update build version to `1.0.0`
Test locally.
OR
> chore: update build version to `1.0.0`

- README.md
chore: update doc links for readme
N/A
OR
> chore: update doc links for readme

- gradle/logto.versions.toml
chore: update build version to `1.1.0`
> chore: update build version to `1.1.0`

- gradle/logto.versions.toml
chore: update build version to `1.1.1`
> chore: update build version to `1.1.1`

- kotlin-sdk/kotlin/src/main/kotlin/io/logto/sdk/core/Core.kt
We should add organization resource in the `generateSignInUri` method in core.
Test locally.
> fix(core): add organization resource in `generateSignInUri` method

- kotlin-sdk/kotlin/src/main/kotlin/io/logto/sdk/core/type/Organization.kt
- kotlin-sdk/kotlin/src/main/kotlin/io/logto/sdk/core/type/UserInfoResponse.kt
- kotlin-sdk/kotlin/src/test/kotlin/io/logto/sdk/core/CoreFetchTest.kt
- kotlin-sdk/kotlin/src/test/kotlin/io/logto/sdk/core/type/OrganizationTest.kt
- kotlin-sdk/kotlin/src/test/kotlin/io/logto/sdk/core/type/UserInfoResponseTest.kt
Add organization data to userinfo response
Test locally & UI covered.
> feat(core): add organization data to userinfo response

- gradle/logto.versions.toml
chore: update build version to `1.1.3`
No need
~~- [ ] `.changeset`~~
~~- [ ] unit tests~~
~~- [ ] integration tests~~
~~- [ ] necessary TSDoc comments~~
> chore: update build version to `1.1.3`

- README.md
refactor: update sdk tutorial link
N/A
> refactor: update sdk tutorial link

- .github/workflows/commitlint.yml
Fix commitlint CI, since the @commitlint/config-conventional package has became a ESM module, so we need to update the config file accordingly.
CI passed.
> ci: fix commitlint task

- android-sdk/android/src/main/kotlin/io/logto/sdk/android/auth/logto/LogtoAuthSession.kt
- android-sdk/android/src/test/kotlin/io/logto/sdk/android/auth/logto/LogtoAuthSessionTest.kt
- kotlin-sdk/kotlin/src/main/kotlin/io/logto/sdk/core/Core.kt
- kotlin-sdk/kotlin/src/main/kotlin/io/logto/sdk/core/type/GenerateSignInUriOptions.kt
- kotlin-sdk/kotlin/src/test/kotlin/io/logto/sdk/core/CoreTest.kt
Introduce `GenerateSignInUriOptions` to prepare for the upcoming PR.
Test locally & UT
> feat!: introduce `GenerateSignInUriOptions`

- android-sdk/android/src/main/kotlin/io/logto/sdk/android/LogtoClient.kt
- android-sdk/android/src/main/kotlin/io/logto/sdk/android/auth/logto/LogtoAuthManager.kt
- android-sdk/android/src/main/kotlin/io/logto/sdk/android/auth/logto/LogtoAuthSession.kt
- android-sdk/android/src/main/kotlin/io/logto/sdk/android/type/LogtoConfig.kt
- android-sdk/android/src/main/kotlin/io/logto/sdk/android/type/SignInOptions.kt
- android-sdk/android/src/test/kotlin/io/logto/sdk/android/auth/logto/LogtoAuthManagerTest.kt
- android-sdk/android/src/test/kotlin/io/logto/sdk/android/auth/logto/LogtoAuthSessionTest.kt
Add sign-in options for android sdk
All UTs passed.
> feat(android-sdk): add sign-in options for android sdk

- gradle/logto.versions.toml
update build version to `2.0.0`
No need.
~~- [ ] `.changeset`~~
~~- [ ] unit tests~~
~~- [ ] integration tests~~
~~- [ ] necessary TSDoc comments~~
> chore: update build version to `2.0.0`
